defaults: &defaults
  name: Mass Semantic
  oauth: &oauth
    github: &github
      callback: /usersessions/github/callback
      client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
      secret_key: <%= ENV['GITHUB_CLIENT_SECRET'] %>
    stackex: &stackex
      callback: /usersessions/stackex/callback
      client_id: <%= ENV['STACKEX_CLIENT_ID'] %>
      client_key: <%= ENV['STACKEX_CLIENT_KEY'] %>
      secret_key: <%= ENV['STACKEX_CLIENT_SECRET'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
