defaults: &defaults
  name: Mass Semantic

development:
  <<: *defaults
  oauth:
    github:
      client_id: 845418bb1a00b1aaf8c7
      secret_key: <%= ENV['github_client_secret'] %>
    stackex:
      client_id: 5468
      client_key: 2xLiDuoyp)zKwxapJzzO1g((
      secret_key: <%= ENV['stackex_client_secret'] %>

test:
  <<: *defaults

production:
  <<: *defaults
