defaults: &defaults
  name: Mass Semantic

development:
  <<: *defaults
  github:
    client_id: "845418bb1a00b1aaf8c7"
  stackex_client_id: "5468"
  stackex_client_key: "2xLiDuoyp)zKwxapJzzO1g(("

test:
  <<: *defaults

production:
  <<: *defaults
